name: chess

services:
    server:
        image: ghcr.io/manangandhi1810/chess-server
        restart: unless-stopped
        ports:
            - 3000:3000/tcp
            - 4000:4000/tcp
        volumes:
            - ./server/.env:/appuser/.env
            # - /path/to/ssl/fullchain.pem:/usr/src/app/ssl/fullchain.pem
            # - /path/to/ssl/privkey.pem:/usr/src/app/ssl/privkey.pem
        command: sh -c "npx prisma migrate deploy && npm run start"

    postgresql:
        image: bitnami/postgresql:latest
        restart: unless-stopped
        ports:
            - "5432:5432/tcp"
        volumes:
            - pg-data:/bitnami/postgresql
        environment:
            - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_user
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=postgres
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

    redis:
        image: bitnami/redis:latest
        restart: unless-stopped
        ports:
            - "6379:6379/tcp"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

volumes:
    pg-data:
