name: Android Release

on:
  push:
    branches:  [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16"
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start Android Release Build
        run: flutter build apk --release
     
      - name: Upload Android Build Files
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: ./build/app/outputs/flutter-apk

  deploy:
    name: Deploy Android Build
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Android Release
      uses: actions/download-artifact@v2
      with:
        name: android-release

    - name: Push to app-release branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: app-release